remote_theme: saifkhichi96/simple-material

# theme customization
title: Saif Khan
tagline: Mobile Developer and ML Engineer
baseurl: https://saifkhichi96.github.io
logo: /assets/images/logo.png

layout: project
categories: app, featured
keywords: developer tool, requirements engineering
device: Mobile App
description: A collaborative tool for software management with focus on requirements engineering.
icon: /assets/images/projects/recatalyst-logo.png
