theme: saifkhichi96/simple-material

title: Saif Khan
tagline: Mobile Developer and ML Engineer
baseurl: https://saifkhichi96.github.io

categories: app, featured
keywords: developer tool, requirements engineering
device: Mobile App
description: A collaborative tool for software management with focus on requirements engineering.
icon: /assets/images/projects/recatalyst-logo.png
